### PR TITLE
Redirect to log in form

### PR DESCRIPTION
**Pull request by adriana-alter**

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
No :(
I'm not sure what the right way to do this in Python/Flask would be (this is also a new incognito window):
screen shot 2019-01-30 at 5 08 02 pm

**Comment by adriana-alter** [comment]
@EdwinGuzman Try this one: https://github.com/NYPL-Simplified/library_registry/pull/95

**Comment by EdwinGuzman** [comment]
Yes, that fixes it, but why not just update this PR instead of creating a new one? I don't know if that's a good way to fix it in flask so it'd be good to get another opinion.

**Comment by EdwinGuzman** [comment]
Alright. I'll close this one then since you have two.

**Pull request closed without merging**
